project_id = "agzctvizkhkktnuodoxa"

[functions.admin-data]
verify_jwt = false

[functions.process-pending-withdrawals]
verify_jwt = false

[functions.process-withdrawal]
verify_jwt = false

[functions.purchase-tickets]
verify_jwt = false

[functions.get-sol-price]
verify_jwt = false

[functions.initialize-draws]
verify_jwt = false

[functions.draw-winners]
verify_jwt = false
