project_id = "agzctvizkhkktnuodoxa"

[functions.admin-data]
verify_jwt = false

[functions.process-pending-withdrawals]
verify_jwt = false

[functions.process-withdrawal]
verify_jwt = false

[functions.purchase-tickets]
verify_jwt = false

[functions.get-sol-price]
verify_jwt = false

[functions.initialize-draws]
verify_jwt = false

[functions.draw-winners]
verify_jwt = false

[functions.toggle-test-mode]
verify_jwt = false

[functions.control-test-lottery]
verify_jwt = false

[functions.reset-test-data]
verify_jwt = false
